name: "Lints"
on:
  push:
  pull_request:

jobs:
  check:
    name: cargo check
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: tecolicom/actions-use-apt-tools@v1
        with:
          tools: libgtk-3-dev g++ pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0 libwayland-dev libxkbcommon-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libatk1.0-dev
          cache: yes
      - run: cargo check
