name: "Compile release binaries"
on:
  release:
    types: [published, edited]

jobs:
  build_x64_linux:
    name: Build x86_64 Linux
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 'stable, 1.84.0'
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: >
            libgtk-3-dev g++ pkg-config libx11-dev libasound2-dev libudev-dev 
            libxkbcommon-x11-0 libwayland-dev libxkbcommon-dev libxcb-render0-dev 
            libxcb-shape0-dev libxcb-xfixes0-dev libatk1.0-dev
          version: 1.0

      - name: "Build and rename the executable"
        run: |
          cargo build --profile=hyperoptimize
          mv target/hyperoptimize/fractality ./fractality-linux-x86_64

      - uses: AButler/upload-release-assets@v3.0
        with:
          files: "./fractality-linux-x86_64"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  
  build_i686_linux:
    name: Build i686 Linux
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 'stable, 1.84.0'
          target: i686-unknown-linux-gnu
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: >
            libgtk-3-dev g++ pkg-config libx11-dev libasound2-dev libudev-dev 
            libxkbcommon-x11-0 libwayland-dev libxkbcommon-dev libxcb-render0-dev 
            libxcb-shape0-dev libxcb-xfixes0-dev libatk1.0-dev
          version: 1.0

      - name: "Build and rename the executable"
        run: |
          cargo build --profile=hyperoptimize --target=i686-unknown-linux-gnu
          mv target/hyperoptimize/fractality ./fractality-linux-i686

      - uses: AButler/upload-release-assets@v3.0
        with:
          files: "./fractality-linux-i686"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
